version: "3.3"
services:
  bot:
    build: .
    restart: always
    environment:
      TZ: ${TZ}
      BOT_TOKEN: ${BOT_TOKEN}
      OWNER_ID: ${OWNER_ID}
      MAX_INVITES_PER_USER: ${MAX_INVITES_PER_USER}
      EXPIRY_HOURS: ${EXPIRY_HOURS}
    volumes:
      - ./invitebot.sqlite3:/app/invitebot.sqlite3:ro
